### PR TITLE
Update for compatibility with Angular 4+

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Still need a way to package the code. Could use the Angular Firebase method with a `build.ts` or [ng-packgr](https://github.com/dherges/ng-packagr).

Any preference, @mujtaba-ahmad?

**Comment by mujtaba-ahmad** [comment]
@cmckni3 Thanks for your pull request, i will have a look at it and will merge it with master.

**Comment by cmckni3** [comment]
Excellent. Any thoughts on compiling to JS?

**Comment by cmckni3** [comment]
Any updates?

**Comment by cmckni3** [comment]
Any updates @mujtaba-ahmad? I may publish my forked version if no response.

**Pull request closed without merging**
